#!/usr/bin/env sh

. utils.sh

[ "$(id -u)" -eq 0 ] && die 'cannot be run as root'

usage() {
	cat <<-_EOF
		usage: ${BOLD}$PROGRAM${NORMAL} [ ${ITALIC}DOAS OPTIONS${NORMAL} ] ${ITALIC}file${NORMAL}
		Open ${ITALIC}file${NORMAL} with current user \$EDITOR (${ITALIC}$EDITOR${NORMAL})
		${ITALIC}DOAS OPTIONS${NORMAL} is options passed to doas(1)
	_EOF
}

eval set -- "$("$GETOPT" -o hLnsC:u: -name -l help -n "$PROGRAM" -- "$@")"

add_opt() {
	opts="${opts}$1 "
}
while true; do
	case $1 in
	-h | --help)
		shift
		usage && exit 0
		;;
	--)
		shift
		break
		;;
	-C | -u)
		add_opt "$@"
		shift
		add_opt "$@"
		shift
		;;
	*)
		add_opt "$@"
		shift
		;;
	esac
done

[ $# -lt 1 ] && usage && exit 1

file=$(realpath "$1")
[ "$file" = "" ] && die 'missing file operand'

# Save file dir if file not exist
[ ! -f "$file" ] && dir="$(dirname -- "$file")"

[ -w "$file" -o -w "$dir" ] &&
	die 'editing writable file is not permitted'

tempdir=$(mktemp -d)
tempfile="$tempdir"/${file##*/}

if [ "$dir" ]; then
	# Save dir ownership
	ownership="$(stat -c '%u:%g' "$dir")"
else
	# Save file ownership
	ownership="$(stat -c '%u:%g' "$file")"
	# Copy original file with preserved attributes
	cp --preserve=all "$file" "$tempfile"
fi

"$EDITOR" "$tempfile"

if [ -f "$tempfile" ] && ! cmp -s "$file" "$tempfile"; then
	# sh is need for
	# 1) use script without persist in doas.conf
	# 2) single doas authentication
	eval doas "$opts \
  sh -c '
  mv $tempfile $file
	chown $ownership $file'"
	rm -rf "$tempdir"
fi
