#!/usr/bin/env bash
# .profile

add_path() {
	export PATH="$PATH:${1%:}"
}

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# shell
export SHELL_CONFIG_HOME="$XDG_CONFIG_HOME/shell"
export INPUTRC="$SHELL_CONFIG_HOME/inputrc"
[ -f "$SHELL_CONFIG_HOME/bashrc" ] && source "$SHELL_CONFIG_HOME/bashrc"

# X11
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

# Default programs
export EDITOR='nvim'
export TERMINAL='st'
export PAGER='less'

# Program settings
export ANDROID_SDK_ROOT="$HOME/android"                 # Set the root dir for android sdk
export SSH_AUTH_SOCK="${TMPDIR:-/tmp}/ssh-agent.socket" # Required to use ssh-agent service

# Clean up ~/
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export TASKDATA="$XDG_DATA_HOME/task"

# My scripts
export BOOKS_DIR="$HOME/books"
export DIARY_DIR="$HOME/notes/diary"
export GOAL_FILE="$XDG_DATA_HOME/scripts/goal"
export EMOJI_FILE="$XDG_DATA_HOME/scripts/emoji"

# Program options
export _JAVA_AWT_WM_NONREPARENTING=1  # Fix for Java applications in dwm
export GTEST_COLOR=1                  # Google test framework output colorful
export LESS='-M -F -I -R --incsearch' # Set up less
export LESSOPEN='| lesspipe.sh %s'    # Syntax highlighting

# Add local scripts and programs to PATH
add_path "$(find ~/.local/bin -type d ! -path '*/\.git*' -printf %p:)"
add_path "$XDG_DATA_HOME/nvim/mason/bin"
add_path "$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/tools"
add_path "$GOPATH/bin"

# Automatic startx
[ "$(tty)" = '/dev/tty1' ] && ! pidof -s 'Xorg' >/dev/null 2>&1 && exec startx "$XINITRC" || true
