#!/usr/bin/env bash
# .profile

add_path() {
	export PATH="${1%:}:$PATH"
}

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

# shell
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
[ -r "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# X11
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"

# Default programs
export EDITOR='nvim'
export TERMINAL='alacritty'
export PAGER='less'
export BROWSER='firefox'

# Program settings
export ANDROID_SDK_ROOT="$HOME/android"                         # Set the root dir for android sdk
export SSH_AUTH_SOCK="${TMPDIR:-/tmp}/ssh-agent.${USER}.socket" # Required to use ssh-agent service
export SVDIR="$XDG_DATA_HOME/service"

# Clean up ~/
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GOPATH="$XDG_DATA_HOME/go"
export TASKLITE_PATH="$XDG_DATA_HOME/tasklite"

# My scripts
export BOOKS_DIR="$HOME/books"
export DIARY_DIR="$HOME/notes/diary"
export FLASHCARDS_DIR="$XDG_DATA_HOME/flashcards/"
export GOAL_FILE="$XDG_DATA_HOME/scripts/goal"
export VOLUME_MIXER="pamixer"
export WIREGUARD_INTERFACE='wg0'

# Program options
export _JAVA_AWT_WM_NONREPARENTING=1  # Fix for Java applications in dwm
export GTEST_COLOR=1                  # Google test framework output colorful
export LESS='-M -F -I -R --incsearch' # Set up less
export LESSOPEN='| lesspipe.sh %s'    # Syntax highlighting

# Add local scripts and programs to PATH
add_path "$(find ~/.local/bin -type d ! -path '*/\.git*' -printf %p:)"
add_path "$XDG_DATA_HOME/nvim/mason/bin"
add_path "$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/tools"
add_path "$CARGO_HOME/bin"
add_path "$GOPATH/bin"
add_path "$HOME/.nix-profile/bin"

#Automatic startx
command -v startx >/dev/null 2>&1 && [ "$(tty)" = '/dev/tty1' ] && ! pidof -s 'Xorg' >/dev/null 2>&1 && exec startx "$XINITRC" || true

[ -f "/home/subado/.ghcup/env" ] && . "/home/subado/.ghcup/env" # ghcup-env