#!/usr/bin/env sh

xkeyboard-setup.sh
setbg
xcompmgr &
laptop_keyboard=$(xinput list | grep 'AT Translated')
[ "$laptop_keyboard" ] && xinput float "$(awk '{print $7}' <<<"$laptop_keyboard" | awk -F '=' '{print $2}')"
